### ISSUE TITLE
throwing errors in httprobe 

### ISSUE THREAD

**Issue by subhash0x** [Dheerajmadhukar/karma_v2#14] opened 2022-01-15 04:45 UTC
i have installed httprobe but one of my machines showing it's not installed 

and on my vps it's showing this error -

```

flag provided but not defined: -prefer-https
Usage of httprobe:
  -c int
        set the concurrency level (default 20)
  -p value
        add additional probe (proto:port)
  -s    skip the default probes (http:80 and https:443)
  -t int
        timeout (milliseconds) (default 10000)
  -v    output errors to stderr
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list
```

**Comment by Dheerajmadhukar** [comment] 2022-01-15 07:45
Duplicate of https://github.com/Dheerajmadhukar/karma_v2/issues/1

**Closed by Dheerajmadhukar** 2022-01-15 07:45 UTC
