### ISSUE TITLE
Problem with interlace

### ISSUE THREAD

**Issue by Thxny881** [Dheerajmadhukar/karma_v2#24] opened 2024-03-07 23:34 UTC
![Screenshot_2024-03-07_20_30_50](https://github.com/Dheerajmadhukar/karma_v2/assets/145889227/08f10a62-4548-4fe0-ad6f-a41ec44fcaff)

I'm having problem with interlace, i uninstalled and installed again, but don't resolve

**Comment by detecht-MK** [comment] 2024-03-08 21:04
![karma-output](https://github.com/Dheerajmadhukar/karma_v2/assets/162750302/cf29528c-e72c-444d-999a-4810f1524abc)

I've been having a similar issue since I first started using Karma_v2 a couple months ago. I'm guessing I probably did something wrong, but I don't know what it is. Any help pin pointing the cause would be greatly appreciated! Thank you!

**Comment by Dheerajmadhukar** [comment] 2024-03-08 21:07
Yes I am aware of this issue, and it's also already fixed in new version which I will publish very soon. Keep in touch  :)

**Comment by detecht-MK** [comment] 2024-03-08 21:07
Awesome! Thank you very much.

**Comment by Thxny881** [comment] 2024-03-08 21:14
> @Thxny881 mate it's because of your shodan credits. It's ZERO

The files where the results are located are blank, is it because I don't have shodan credits either ?

**Comment by Dheerajmadhukar** [comment] 2024-03-08 21:15
Yes ! Due to no credits the inscopes ips are not available to proceed with interlace.

**Closed** 2024-03-15 17:04 UTC

**Comment by devileyes10** [comment] 2024-05-31 04:41
> @Thxny881 mate it's because of your shodan credits. It's ZERO

Hello man! Do we need to have both Query Credet and Scan Credit available? Thank you

**Comment by Dheerajmadhukar** [comment] 2024-05-31 05:12
Yo just need query credits !

**Comment by devileyes10** [comment] 2024-05-31 05:30
> Yo just need query credits !

thank you mate

**Comment by LowLevelJody** [comment] 2024-10-23 14:36
i have the same issue and my credit are still 100. i confused on what should i do
